version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real-estate-tenant-fe
    ports:
      - "3002:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - NEXT_PUBLIC_TYPESENSE_HOST=${NEXT_PUBLIC_TYPESENSE_HOST}
      - TYPESENSE_HOST=${NEXT_PUBLIC_TYPESENSE_HOST}
      - NEXT_PUBLIC_TYPESENSE_PORT=${NEXT_PUBLIC_TYPESENSE_PORT}
      - NEXT_PUBLIC_TYPESENSE_API_KEY=${NEXT_PUBLIC_TYPESENSE_API_KEY}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3002}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3002/api}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    networks:
      - backend_network
    restart: always

networks:
  backend_network:
    external: true
    name: real-estate-tenant-be_default
